console.log("This is a nodeJs program");
console.log("The change is in master branch");
console.log("Add a new change");
console.log("Add a merge");
console.log("Add another log");
console.log("Add a a new change to test merge logs after branches are merged");
console.log("Add a a new change to test merge logs after branches are rebased");
console.log("Add a log in feature branch rebased");
console.log("Add another log in feature branch rebased");
console.log("Add another log ");
console.log("Add another  another log ");
